name 'demo_ssh'
maintainer 'Jeff Mery'
maintainer_email 'jmery@chef.io'
license 'all_rights'
description 'Configures basic SSH'
long_description 'Configures basic SSH'
issues_url 'https://github.com/jmery/demo_ssh/issues'
source_url 'https://github.com/jmery/demo_ssh'
version '0.1.0'
